baseURL = "https://istgyanendra.github.io/fac"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "fac"
title = "Finance and Analytics Club"
publishDir = "docs"
[Languages.en]
contentDir = "content/english"
copyright = ""
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.en.menu.footer]]
URL = "events"
name = "Events"
weight = 3
[[Languages.en.menu.footer]]
URL = "team"
name = "Our Team"
weight = 4

[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = ""
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "project"
name = "Project"
weight = 3
[[Languages.en.menu.main]]
URL = "events"
name = "Events"
weight = 4
[[Languages.en.menu.main]]
URL = "team"
name = "Our Team"
weight = 5
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 7


[params]
author = "Finance and Analytics Club"
contact_form_action = "sendmail.php"
description = "The Finance and Analytics Club, IIT Kanpur is one of the largest professional clubs on campus, hosting a full schedule of events to help everyone from those with no background in finance to those coming from finance looking to switch focus within the industry."
email = "fdgiitk@gmail.com"
google_analitycs_id = ""
location = "IIT KANPUR"
logo = "images/logo.png"
mobile = "#"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "26.512404"
map_longitude = "80.232993"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
